name: Deploy updates

on:
  push:

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, 'dont-deploy') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Build page
        run: yarn && yarn deploybuild -u "Khang <khang.nguyenduyvn@gmail.com>"
