name: Deploy updates

on:
  push:
    branches:
      - v1

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, 'no-deploy') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Build page
        run: |
          yarn
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploybuild -u "Khang <khang.nguyenduyvn@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
