name: Deploy updated content
on:
  push:
    paths: "**.md"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: main
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: src/.vuepress/dist/
